version: "3.5"
services:
  backend:
    container_name: casting
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: "mysql:5.7.24"
    container_name: "dbcontainer"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "tonitonitoni"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "tonitonitoni"
      MYSQL_DATABASE: "casting_dev"
